name: Run Specific Cucumber Feature Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The virtual machine where the job will run

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (or any required JDK version)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Step 3: Cache Maven dependencies (optional)
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project (skip tests to speed up the process)
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      # Step 5: Run specific Cucumber feature test (LoginPage.feature)
      - name: Run Specific Cucumber Feature Test (LoginPage.feature)
        run: mvn test -Dcucumber.options="classpath:Features/Swag/LoginPage.feature"
        # This will run the specific LoginPage.feature test

      # Step 6: Upload Cucumber test results as artifacts
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: target/cucumber-reports/Cucumber.html  # Adjust this to the actual location of your Cucumber report
